FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY . .

RUN dotnet restore "NordClan.BookingApp.Client/NordClan.BookingApp.Client.csproj"

RUN dotnet publish "NordClan.BookingApp.Client/NordClan.BookingApp.Client.csproj" -c Release -o /app/build

FROM nginx:alpine AS final
COPY --from=build /app/build/wwwroot /usr/share/nginx/html

COPY NordClan.BookingApp.Client/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
ENTRYPOINT ["nginx", "-g", "daemon off;"]
